- hosts: localhost
  tasks:
  - name: insall postgres 10 repo
    yum:
      name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm

  - name: insall postgres 10 server
    yum:
      name: postgresql10-server

  # steps from /usr/share/doc/postgresql10-10.4/README.rpm-dist
  - name: init db
    shell: /usr/pgsql-10/bin/postgresql-10-setup initdb
    ignore_errors: yes

  - name: start postgres
    systemd:
      name: postgresql-10.service
      enabled: yes
      state: started
